//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    
    public enum CategoryNames : int
    {
        Beverages = 1,
        Condiments = 2,
        Confections = 3,
        DairyProducts = 4,
        GrainsCereals = 5,
        MeatPoultry = 6,
        Produce = 7,
        Seafood = 8,
        Wine = 9
    }
}
